import { useEffect, useState } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
    import.meta.env.VITE_SUPABASE_ANON_KEY
    )

    function App() {
      const [categorias, setCategorias] = useState([])
        const [productos, setProductos] = useState([])

          useEffect(() => {
              fetchMenu()
                }, [])

                  async function fetchMenu() {
                      // Traemos categorías y productos al mismo tiempo
                          const resCat = await supabase.from('categorias').select('*').order('orden')
                              const resProd = await supabase.from('productos').select('*').eq('stock', true)
                                  
                                      setCategorias(resCat.data || [])
                                          setProductos(resProd.data || [])
                                            }

                                              return (
                                                  <div style={styles.container}>
                                                        <header style={styles.header}>
                                                                <h1 style={styles.title}>Nuestro Menú</h1>
                                                                        <p style={styles.subtitle}>Mesa #01</p>
                                                                              </header>

                                                                                    {categorias.map(cat => (
                                                                                            <section key={cat.id} style={styles.section}>
                                                                                                      <h2 style={styles.categoryTitle}>{cat.nombre}</h2>
                                                                                                                
                                                                                                                          <div style={styles.grid}>
                                                                                                                                      {productos
                                                                                                                                                    .filter(p => p.categoria_id === cat.id)
                                                                                                                                                                  .map(prod => (
                                                                                                                                                                                  <div key={prod.id} style={styles.card}>
                                                                                                                                                                                                    <div style={styles.cardInfo}>
                                                                                                                                                                                                                        <h3 style={styles.prodName}>{prod.nombre}</h3>
                                                                                                                                                                                                                                            <p style={styles.prodDesc}>{prod.descripcion}</p>
                                                                                                                                                                                                                                                                <span style={styles.price}>${prod.precio}</span>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                    <button style={styles.addButton}>+</button>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                // Estilos livianos para que se vea bien en celular
                                                                                                                                                                                                                                                                                                                                                                const styles = {
                                                                                                                                                                                                                                                                                                                                                                  container: { padding: '15px', backgroundColor: '#f9f9f9', minHeight: '100vh', fontFamily: 'sans-serif' },
                                                                                                                                                                                                                                                                                                                                                                    header: { textAlign: 'center', marginBottom: '30px' },
                                                                                                                                                                                                                                                                                                                                                                      title: { fontSize: '28px', color: '#333' },
                                                                                                                                                                                                                                                                                                                                                                        subtitle: { color: '#666', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                          section: { marginBottom: '25px' },
                                                                                                                                                                                                                                                                                                                                                                            categoryTitle: { borderBottom: '2px solid #ffcc00', paddingBottom: '5px', color: '#444' },
                                                                                                                                                                                                                                                                                                                                                                              grid: { display: 'flex', flexDirection: 'column', gap: '15px', marginTop: '10px' },
                                                                                                                                                                                                                                                                                                                                                                                card: { 
                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#fff', 
                                                                                                                                                                                                                                                                                                                                                                                        padding: '15px', 
                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: '12px', 
                                                                                                                                                                                                                                                                                                                                                                                                display: 'flex', 
                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent: 'space-between', 
                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                            boxShadow: '0 2px 5px rgba(0,0,0,0.05)' 
                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                prodName: { margin: '0 0 5px 0', fontSize: '18px' },
                                                                                                                                                                                                                                                                                                                                                                                                                  prodDesc: { margin: '0 0 10px 0', fontSize: '14px', color: '#777' },
                                                                                                                                                                                                                                                                                                                                                                                                                    price: { fontWeight: 'bold', color: '#2ecc71', fontSize: '18px' },
                                                                                                                                                                                                                                                                                                                                                                                                                      addButton: { 
                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#ffcc00', 
                                                                                                                                                                                                                                                                                                                                                                                                                              border: 'none', 
                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '50%', 
                                                                                                                                                                                                                                                                                                                                                                                                                                      width: '35px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                          height: '35px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: '20px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: 'pointer' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default App
